from __future__ import annotations

from typing import Literal
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator

from models.research_taxonomy import ALLOWED_RESEARCH_TOPICS

EntityType = Literal["project", "expert", "funder", "enterprise"]


class RecommendationRequest(BaseModel):
    project_id: Optional[str] = Field(
        default=None,
        description="Project identifier (e.g. PRJ_0001)",
    )
    expert_id: Optional[str] = Field(
        default=None,
        description="Expert identifier when recommending projects for an expert",
    )
    limit: int = Field(5, ge=1, le=100, description="Maximum number of recommendations")
    language: str = Field(
        "vi",
        description="Language for natural-language explanations",
    )
    source_id: Optional[str] = Field(
        default=None,
        description="Generic source id for policy-based recommendation",
    )
    source_type: Optional[EntityType] = Field(
        default=None,
        description="Source entity type in policy graph",
    )
    target_type: Optional[EntityType] = Field(
        default=None,
        description="Target entity type to recommend in policy graph",
    )
    target_id: Optional[str] = Field(
        default=None,
        description="Specific target entity id when evaluating one selected entity",
    )
    mode: Literal["personal", "public", "admin_debug"] = Field(
        "public",
        description="Recommendation visibility mode for provisional KG data",
    )
    current_user_id: Optional[str] = Field(
        default=None,
        description="Current user id for personal-mode recommendation filters",
    )


class ExplanationSchema(BaseModel):
    natural_language: str = Field(..., description="Human-readable explanation text")
    visualization: str = Field(..., description="Visualization payload or URL")


class RecommendationItem(BaseModel):
    id: str = Field(..., description="Recommended object identifier")
    name: str = Field(..., description="Recommended object display name")
    score: float

    explanation: Optional[ExplanationSchema] = Field(
        default=None,
        description="Structured explanation for this recommendation",
    )
    metrics: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional ranking metrics used by recommendation engine",
    )
    # Compatibility bridge for current service output shape.
    expert_id: Optional[str] = None
    xai_explanation: Optional[str] = None
    extra: Optional[Dict[str, Any]] = None
    
    # Reasoning paths so that Pydantic doesn't filter them out
    reasoning_paths: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description="List of reasoning paths generated by PGPR",
    )
    path_diversity: Optional[int] = Field(
        default=None,
        description="Number of paths connecting the entities",
    )
    final_score: Optional[float] = None
    raw_score: Optional[float] = None
    stored_trust_weight: Optional[float] = None
    runtime_source_weight: Optional[float] = None
    trust_override_reason: Optional[str] = None
    uses_provisional_data: Optional[bool] = None
    provisional_nodes_count: Optional[int] = None
    data_quality_level: Optional[str] = None
    data_quality_notes: Optional[List[str]] = None
    verification_badges: Optional[Dict[str, Any]] = None
    scoring_method: Optional[str] = Field(
        default=None,
        description="pgpr_policy | cypher_fallback | hybrid_embedding_path | hybrid_embedding",
    )
    evidence_level: Optional[str] = Field(
        default=None,
        description="path_supported | embedding_only | fallback_only",
    )
    cold_start: Optional[bool] = None
    embedding_status: Optional[str] = None
    recommendation_mode: Optional[str] = None
    recommendation_readiness: Optional[str] = None
    recommendation_message: Optional[str] = None
    embedding_similarity: Optional[float] = None
    topic_overlap: Optional[float] = None
    fallback_reason: Optional[str] = Field(
        default=None,
        description="Human-readable reason when reasoning_paths are missing or weak",
    )


class RecommendationResponse(BaseModel):
    status: str
    data: List[RecommendationItem]
    count: int = Field(..., ge=0)


# Backward-compatibility alias used by existing service code.
ExpertRecommendation = RecommendationItem


class EmbeddingRecomputeRequest(BaseModel):
    reason: str = Field(default="", description="Why this recompute was requested (audit log)")


class ExplainRecommendationRequest(BaseModel):
    recommendation: Dict[str, Any] = Field(..., description="The recommendation object to explain")
    target_type: EntityType = Field(..., description="The type of the recommended entity")
    source_context: Optional[Dict[str, Any]] = Field(None, description="Context about the source node")
    language: str = Field("vi", description="Language for natural-language explanations")
    mode: Literal["rule", "llm", "auto"] = Field(
        "llm",
        description="rule=fast template; llm=Ollama; auto=try llm then fallback rule",
    )
    force_refresh: bool = Field(
        False,
        description="Bypass service-layer explanation cache and regenerate the explanation",
    )


class ExplanationResponse(BaseModel):
    status: str
    data: Dict[str, Any]


class GraphPathsQuery(BaseModel):
    source_type: EntityType
    source_id: str
    target_type: EntityType
    target_id: str
    max_length: Optional[int] = Field(None, ge=1, le=12)
    limit: int = Field(10, ge=1, le=50)


class GraphPathItem(BaseModel):
    path: str
    score: float
    relations: List[str]
    entities: List[str]
    path_length: int
    explanation: Optional[str] = None


class GraphPathsResponse(BaseModel):
    status: str
    data: List[GraphPathItem]
    count: int = Field(..., ge=0)


class GraphNodeItem(BaseModel):
    id: str
    label: str
    type: str
    properties: Dict[str, Any] = Field(default_factory=dict)


class GraphEdgeItem(BaseModel):
    id: str
    source: str
    target: str
    type: str


class GraphNeighborsData(BaseModel):
    nodes: List[GraphNodeItem]
    edges: List[GraphEdgeItem]


class GraphNeighborsResponse(BaseModel):
    status: str
    data: GraphNeighborsData
    count: int = Field(..., ge=0)


class UserPublic(BaseModel):
    id: str
    email: str
    full_name: str
    username: str = ""
    role: str = "expert"
    account_role: str = "user"
    organization: str = ""
    phone: str = ""
    address: str = ""
    country: str = "VN"
    province: str = ""
    district: str = ""
    skills: List[str] = Field(default_factory=list)
    custom_skills: List[str] = Field(default_factory=list)
    bio: str = ""
    social_links: Dict[str, str] = Field(default_factory=dict)
    profile_data: Dict[str, Any] = Field(default_factory=dict)
    research_interests: List[str] = Field(default_factory=list)
    custom_research_topics: List[str] = Field(default_factory=list)
    linked_entity: Optional[Dict[str, Any]] = None
    account_verification_status: str = "email_unverified"
    status: str = "active"
    created_at: Optional[Any] = None
    updated_at: Optional[Any] = None


class RegisterRequest(BaseModel):
    email: str
    password: str = Field(..., min_length=6)
    full_name: str
    username: str = ""
    role: Literal["expert", "enterprise", "funder"] = "expert"
    organization: str = ""
    phone: str = ""
    address: str = ""
    country: str = "VN"
    province: str = ""
    district: str = ""
    skills: List[str] = Field(default_factory=list)
    custom_skills: List[str] = Field(default_factory=list)
    bio: str = ""
    social_links: Dict[str, str] = Field(default_factory=dict)
    profile_data: Dict[str, Any] = Field(default_factory=dict)
    research_interests: List[str] = Field(default_factory=list)
    custom_research_topics: List[str] = Field(default_factory=list)

    @field_validator("research_interests")
    @classmethod
    def validate_research_interests(cls, value: List[str]) -> List[str]:
        invalid = [item for item in value if item not in ALLOWED_RESEARCH_TOPICS]
        if invalid:
            raise ValueError(f"Unsupported research topics: {', '.join(invalid)}")
        return value


class LoginRequest(BaseModel):
    email: str
    password: str


class AdminCreateUserRequest(BaseModel):
    email: str
    password: str = Field(..., min_length=6)
    full_name: str
    username: str = ""
    role: Literal["expert", "enterprise", "funder"] = "expert"


class AuthData(BaseModel):
    token: str
    user: UserPublic


class AuthResponse(BaseModel):
    status: str
    data: AuthData


class ProfileUpdateRequest(BaseModel):
    full_name: Optional[str] = None
    username: Optional[str] = None
    role: Optional[Literal["expert", "enterprise", "funder"]] = None
    organization: Optional[str] = None
    phone: Optional[str] = None
    address: Optional[str] = None
    country: Optional[str] = None
    province: Optional[str] = None
    district: Optional[str] = None
    skills: Optional[List[str]] = None
    custom_skills: Optional[List[str]] = None
    bio: Optional[str] = None
    social_links: Optional[Dict[str, str]] = None
    profile_data: Optional[Dict[str, Any]] = None
    research_interests: Optional[List[str]] = None
    custom_research_topics: Optional[List[str]] = None

    @field_validator("research_interests")
    @classmethod
    def validate_research_interests(cls, value: Optional[List[str]]) -> Optional[List[str]]:
        if value is None:
            return value
        invalid = [item for item in value if item not in ALLOWED_RESEARCH_TOPICS]
        if invalid:
            raise ValueError(f"Unsupported research topics: {', '.join(invalid)}")
        return value


class ProjectCreateRequest(BaseModel):
    title: str
    summary: str = ""
    description: str = ""
    field: str = ""
    status: str = "draft"
    budget: Optional[float] = None
    trl: Optional[int] = Field(default=None, ge=1, le=9)
    location: str = ""
    keywords: List[str] = Field(default_factory=list)
    basic_info: Optional[Dict[str, Any]] = None
    requirements_and_timeline: Optional[Dict[str, Any]] = None
    rd_profile: Optional[Dict[str, Any]] = None
    relations: Optional[Dict[str, Any]] = None
    follow_up_opportunities: Optional[Dict[str, Any]] = None
    governance: Optional[Dict[str, Any]] = None


class MyProjectsResponse(BaseModel):
    status: str
    data: List[Dict[str, Any]] = Field(default_factory=list)
    count: int = 0
